spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: postgres
    password: admin
  sql:
    init:
      mode: always

server:
  port: 8081

app:
  external:
    base-url: http://localhost:8081
    tarifa-timeout: 1500ms
    clima-timeout: 3000ms
    riesgo-timeout: 800ms
  reservation-ttl: 15m
  expiry-interval: 30s
  risk-threshold: 80
  default-risk-score: 30
  tarifa-base-por-kg: 3500